// hello
pipeline{
    agent any 
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('SonarQube'){
            steps{
               sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mvb5209_2025geoapp'
            }
        }
        stage("maven1"){
            steps{
                sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
                target/bio*.jar \
                "http://3.83.45.185:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
}

